# Generated by Django 5.0.4 on 2024-05-06 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcoesContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Telefone', 'Telefone'), ('Rede_Social', 'Rede Social'), ('Outro', 'Outro')], max_length=50)),
                ('numero_identificador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Financeiro', 'Financeiro'), ('Locomoção', 'Locomoção'), ('Alimentação', 'Alimentação'), ('Outros', 'Outros')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('agenda_disponibilidade', models.ManyToManyField(related_name='cuidadores', to='medassistente.agendadisponivel')),
                ('contatos', models.ManyToManyField(to='medassistente.opcoescontato')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medassistente.cuidador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
