# Generated by Django 5.0.4 on 2024-05-07 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medassistente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocuidador',
            name='senha',
            field=models.CharField(default=datetime.datetime(2024, 5, 7, 13, 3, 9, 27743), max_length=128),
            preserve_default=False,
        ),
    ]
