# Generated by Django 5.0.4 on 2024-05-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_usuario_principal_usuariovinculado_usuario_principal_id'),
        ('medassistente', '0002_usuariocuidador_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariovinculado'),
        ),
    ]
