# Generated by Django 5.0.4 on 2024-05-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_usuario_principal_usuariovinculado_usuario_principal_id'),
        ('medassistente', '0003_alter_cuidador_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocuidador',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='agendadisponivel',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariovinculado'),
        ),
        migrations.AddField(
            model_name='agendadisponivel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuidador',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcoescontato',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariovinculado'),
        ),
        migrations.AddField(
            model_name='opcoescontato',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recursodisponivel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='contatos',
            field=models.ManyToManyField(related_name='opcoes_contato', to='medassistente.opcoescontato'),
        ),
    ]
