# Generated by Django 5.0.4 on 2024-05-08 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovinculado',
            name='senha',
            field=models.CharField(default=datetime.datetime(2024, 5, 8, 21, 48, 8, 689928), max_length=128),
            preserve_default=False,
        ),
    ]
