# Generated by Django 5.0.4 on 2024-05-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuariovinculado_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariovinculado',
            old_name='usuario_principal',
            new_name='usuario_principal_id',
        ),
    ]
