# Generated by Django 5.0.4 on 2024-05-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afericao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aferitivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_resultante', models.CharField(max_length=20)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afericao.instrumentoafericao')),
            ],
        ),
    ]
