# Generated by Django 5.0.4 on 2024-05-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afericao', '0002_aferitivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosaferitivos',
            name='aferitivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afericao.aferitivos'),
            preserve_default=False,
        ),
    ]
