# Generated by Django 5.0.4 on 2024-05-10 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_usuario_principal_usuariovinculado_usuario_principal_id'),
        ('afericao', '0003_resultadosaferitivos_aferitivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosaferitivos',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariovinculado'),
        ),
        migrations.AddField(
            model_name='resultadosaferitivos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
