# Generated by Django 5.0.4 on 2024-05-10 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimento', models.CharField(choices=[('CA', 'Café da Manhã'), ('AL', 'Almoço'), ('JA', 'Jantar'), ('LA', 'Lanche'), ('OU', 'Outro')], max_length=2)),
                ('descricao', models.TextField()),
                ('hora_consumo', models.DateTimeField()),
                ('calorias', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscalaQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveSmallIntegerField(choices=[(0, 'Ruim'), (1, 'Muito Ruim'), (2, 'Ruim'), (3, 'Abaixo do Esperado'), (4, 'Adequado'), (5, 'Bom'), (6, 'Bem'), (7, 'Muito Bem'), (8, 'Ótimo'), (9, 'Excelente'), (10, 'Ótimo')], default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Liquido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_liquido', models.CharField(choices=[('AG', 'Água'), ('SU', 'Suco'), ('RE', 'Refrigerante'), ('CH', 'Chá'), ('OU', 'Outro')], max_length=2)),
                ('descricao', models.TextField()),
                ('hora_consumo', models.DateTimeField()),
                ('volume_ml', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAlimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(default=django.utils.timezone.now)),
                ('alimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricao.alimentacao')),
                ('qualidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutricao.escalaquantidade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLiquidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(default=django.utils.timezone.now)),
                ('liquido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricao.liquido')),
                ('quantidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutricao.escalaquantidade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
