# Generated by Django 5.0.4 on 2024-05-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_usuario_principal_usuariovinculado_usuario_principal_id'),
        ('nutricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroalimentacao',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariovinculado'),
        ),
        migrations.AddField(
            model_name='registroliquidos',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariovinculado'),
        ),
    ]
