# Generated by Django 5.0.4 on 2024-05-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_usuario_principal_usuariovinculado_usuario_principal_id'),
        ('farmacia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentoestoque',
            options={},
        ),
        migrations.RenameField(
            model_name='movimentoestoque',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='estoque',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariovinculado'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamentoextendido',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='operacao',
            field=models.CharField(choices=[('AD', 'Adição'), ('RE', 'Remoção')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
